name: Build APK

on:
  push:
    branches:
      - main  # 触发分支，可根据需要修改
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.x"  # 确保包含 Dart 3.5+
          channel: stable            # 可改为 beta/dev 以获取更新版本

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Locate APK
        run: |
          find build/app/outputs/flutter-apk/ -name "*.apk" -exec echo "APK Path: {}" \;

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk